services:
  # Backend API Service
  - type: web
    name: portfolio-backend
    env: node
    plan: starter
    region: oregon
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: FRONTEND_URL
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: 587
      - key: SMTP_SECURE
        value: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: NOTIFICATION_EMAIL
        sync: false
    healthCheckPath: /api/health

  # Frontend Service
  - type: web
    name: portfolio-frontend
    env: static
    plan: starter
    region: oregon
    buildCommand: cd portfolio && npm install && npm run build
    staticPublishPath: portfolio/dist
    headers:
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-XSS-Protection
        value: 1; mode=block
    envVars:
      - key: VITE_API_URL
        sync: false

  # MySQL Database
  - type: pserv
    name: portfolio-database
    env: docker
    plan: starter
    region: oregon
    dockerfilePath: ./Dockerfile.mysql
    dockerContext: ./backend/database
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
      - key: MYSQL_DATABASE
        value: portfolio_db
      - key: MYSQL_USER
        value: portfolio_user
      - key: MYSQL_PASSWORD
        generateValue: true
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 10

databases:
  - name: portfolio-db
    databaseName: portfolio_db
    user: portfolio_user
    plan: starter
    region: oregon
